import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatIconModule,
  MatSidenavModule,
  MatToolbarModule,
  MatCardModule,
  MatStepperModule,
  MatSelectModule,
  MatTabsModule,
  MatGridListModule,
  MatListModule,
  MatRadioModule,
  MatProgressSpinnerModule,
  MatMenuModule,
  MatSnackBarModule,
  MatDialogModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatTableModule,
  MatExpansionModule,
  MatPaginatorModule
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatSidenavModule,
    MatToolbarModule,
    MatCardModule,
    MatStepperModule,
    MatSelectModule,
    MatTabsModule,
    MatGridListModule,
    MatListModule,
    MatRadioModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatDialogModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatMenuModule,
    MatTableModule,
    MatExpansionModule,
    MatPaginatorModule
  ],
  exports: [
      MatButtonModule,
      MatFormFieldModule,
      MatInputModule,
      MatIconModule,
      MatSidenavModule,
      MatToolbarModule,
      MatCardModule,
      MatStepperModule,
      MatSelectModule,
      MatTabsModule,
      MatGridListModule,
      MatListModule,
      MatRadioModule,
      MatProgressSpinnerModule,
      MatSnackBarModule,
      MatDialogModule,
      MatCheckboxModule,
      MatChipsModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatMenuModule,
      MatTableModule,
      MatExpansionModule,
      MatPaginatorModule
  ]
})
export class MaterialModule { }
